// プランナーQRマップ（PublicPlan Server Core、G-2）: 共有ページ share.html の受信口を server 用 module へ書き出す。
//
// なぜ書き出すか:
//   SharePlan v1 / v2 の受信判定（base64url → zlib → 厳格 JSON → closed schema）は share.html の <script> が
//   Planner 正本（build_share_viewer.py が Python contract から生成）と同じ判定を持っている。server がそれを
//   別実装すると判定がずれる。そこで share.html の該当範囲を **1 文字も変えずに** 切り出し、CommonJS の
//   export を末尾に足しただけの module を api/_qr_map/ に置く。share.html が変わったら本 script を再実行し、
//   tests/qr_map/test_viewer_decoder_drift.mjs が「切り出し結果 == 置いてある module」を固定する。
//
// 切り出す範囲（share.html 内の行マーカー。どちらも 1 回だけ現れることを確認する）:
//   開始: "const SPEC = {"            （SPEC ＝ build 時に Python contract から書き出した定数）
//   終了: "/* ---- geometry"           の直前（受信口 ＋ 表示名 helper subjectName / planTitle まで）
//
//   node tools/qr_map/extract_viewer_decoder.mjs           書き出す
//   node tools/qr_map/extract_viewer_decoder.mjs --check   書き出さずに一致だけ確かめる（不一致なら exit 1）
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const SOURCE_PATH = join(ROOT, "share.html");
export const OUTPUT_PATH = join(ROOT, "api", "_qr_map", "viewer_decoder.generated.js");
const START_MARKER = "const SPEC = {";
const END_MARKER = "/* ---- geometry";

function onlyOnce(text, marker) {
  const first = text.indexOf(marker);
  if (first < 0 || text.indexOf(marker, first + 1) >= 0) {
    throw new Error("marker が 0 回または 2 回以上現れる: " + marker);
  }
  return first;
}

export function buildModule(rawHtml) {
  // checkout の改行（Windows の CRLF 変換）に左右されないよう LF に揃えてから切り出し・hash する。
  // こうすると SOURCE_SHA256 は配置済み Viewer の SHA-256（web_viewer/DEPLOYMENT.md の pin）と同じ値になる。
  const html = rawHtml.replace(/\r\n/g, "\n");
  const start = onlyOnce(html, START_MARKER);
  const end = onlyOnce(html, END_MARKER);
  if (!(start < end)) throw new Error("marker の順序が不正");
  // 行頭から切り出す（START_MARKER は行頭にある）
  const lineStart = html.lastIndexOf("\n", start) + 1;
  const body = html.slice(lineStart, end);
  const sha = createHash("sha256").update(Buffer.from(html, "utf8")).digest("hex");
  return [
    "// AUTO-GENERATED by tools/qr_map/extract_viewer_decoder.mjs — 手で編集しない。",
    "// source: share.html sha256 " + sha,
    "// 共有ページの受信口（SharePlan v1 / v2）をそのまま server で使うための写し。DOM は使わない範囲だけを含む",
    "// （`$` / setStatus は定義だけで呼ばれない）。DecompressionStream / Blob / TextEncoder / TextDecoder は Node 24 の global。",
    "\"use strict\";",
    body.trimEnd(),
    "",
    "module.exports = { SPEC, CODES, decodeFragment, subjectName, planTitle, SOURCE_SHA256: " + JSON.stringify(sha) + " };",
    ""
  ].join("\n");
}

function main() {
  const html = readFileSync(SOURCE_PATH, "utf8");
  const generated = buildModule(html);
  if (process.argv.includes("--check")) {
    const current = readFileSync(OUTPUT_PATH, "utf8").replace(/\r\n/g, "\n"); // checkout の CRLF 変換を無視する
    if (current !== generated) {
      console.error("viewer_decoder.generated.js が share.html と一致しない。再生成が必要。");
      process.exit(1);
    }
    console.log("OK: viewer_decoder.generated.js は share.html と一致");
    return;
  }
  writeFileSync(OUTPUT_PATH, generated, "utf8");
  console.log("wrote " + OUTPUT_PATH);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
